export enum Actions {
  SORT_FIRST_TO_LAST = 'FIRST_TO_LAST',
  SORT_LAST_TO_FIRST = 'LAST_TO_FIRST',
  DELETE_GAME = 'DELETE_GAME',
  OPEN_ADD_MODAL = 'OPEN_MODAL',
  OPEN_CHANGE_POSITION_MODAL = 'OPEN_CHANGE_POSITION_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
  ADD_GAME = 'ADD_GAME',
  CHANGE_GAME_POSITION = 'CHANGE_GAME_POSITION',
  GET_DOWNLOAD_GAME_LIST = 'GET_DOWNLOAD_GAME_LIST',
}
